version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      if [ ! -f /data_loaded.flag ]; then
        python manage.py loaddata seed_data.json &&
        touch /data_loaded.flag;
      fi &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - data_loaded:/data_loaded
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  data_loaded:
