# Generated by Django 4.2.16 on 2024-10-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planesinventory',
            old_name='plane_id',
            new_name='plane',
        ),
    ]
