# Generated by Django 4.2.16 on 2024-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_rename_plane_id_planesinventory_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='required_parts',
            field=models.TextField(default=(1, 2, 3, 4, 5)),
            preserve_default=False,
        ),
    ]
