# Generated by Django 4.2.16 on 2024-10-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_parts', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.planes')),
            ],
        ),
    ]
