# Generated by Django 4.2.16 on 2024-10-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.CreateModel(
            name='PartsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField()),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.parts')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.planes')),
            ],
        ),
    ]
